### ISSUE TITLE
Perhaps this will help someone

### ISSUE THREAD

**Issue by hattmann** [TBertuzzi/Bertuzzi.MAUI.PinchZoomImage#4]
This example code from Microsoft does exact the same, and works for me:

https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/gestures/pinch

Create a pinch container
The PinchToZoomContainer class, which is shown in the following example, is a generalized helper class that can be used to interactively zoom a [View](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.view):

**Comment by TBertuzzi** [comment]
When I created the package, PinchToZoomContainer didn't exist yet ;)
